# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20170916_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='focus',
            field=models.CharField(choices=[('Weight Lifting', 'Weight Lifting'), ('Power Lifting', 'Power Lifting'), ('Cardio', 'Cardio'), ('HIIT', 'HIIT'), ('Plyometrics', 'Plyometrics'), ('Mixed', 'Mixed')], max_length=15, null=True),
        ),
    ]
