# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
