# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.DecimalField(decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.DecimalField(decimal_places=100, max_digits=100, null=True),
        ),
    ]
