# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_remove_preference_user'),
        ('person', '0005_auto_20170917_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='preference.Preference'),
        ),
    ]
