# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='preference',
        ),
    ]
