# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_remove_person_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
