# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_remove_person_preference'),
        ('preference', '0003_remove_preference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person'),
        ),
    ]
